### ISSUE TITLE
Please provide binaries

### ISSUE THREAD

**Issue by eMPee584** [utapyngo/icsmanager#14]
Wanted (well, needed) this on a friend's PC which is ultra slow and has no sensible toolchain..

**Comment by eMPee584** [comment]
Ok I tried it at work today but some wired mess about fragments of NET 4.0 required for the windows SDK required for compiling stopped me short of an exe 😭

**Comment by eMPee584** [comment]
@karlhiramoto @granak @FSLASER
or can someone send me an exe by mail please?

**Comment by eMPee584** [comment]
+ @FullSpectrumLaser

**Comment by granak** [comment]
Try this (WPF powered app using icsmanager):
[HostedNet.zip](https://github.com/utapyngo/icsmanager/files/1272031/HostedNet.zip)

Ics manager bin output:
[icsmanager.zip](https://github.com/utapyngo/icsmanager/files/1272036/icsmanager.zip)

**Comment by eMPee584** [comment]
... by the way, reportedly works fine. Thanks @granak! : )
@utapyngo: maybe these can be linked to from the icsmanager entrance page?
