### ISSUE TITLE
Please provide doc for installing System.Management.Automation

### ISSUE THREAD

**Issue by oliverskawronek** [utapyngo/icsmanager#15]
It seems that `System.Management.Automation` is no longer supported by .NET.
There is an unofficial package https://www.nuget.org/packages/System.Management.Automation.

For me it was simply **Tools** > **NuGet Package Manager** > **Package Manager Console** and type

`PM> Install-Package System.Management.Automation -Version 6.1.7601.17515`

After that, I can build the whole solution without any problems.

Please can you add this information to the project's README?

**Comment by utapyngo** [comment]
Feel free to create a pull request with this information.

**Comment by oliverskawronek** [comment]
Yep https://github.com/utapyngo/icsmanager/pull/16

**Comment by utapyngo** [comment]
Merged.
